### ISSUE TITLE
Pick the drive containing your EFI:

### ISSUE THREAD

**Issue by ghost** [corpnewt/EssentialsList#2]

**Comment by ghost** [comment]
and there is no option to pick
try uuid and shown : invalid disk

**Comment by corpnewt** [comment]
Does the drive in question have an EFI partition?  What is the output of `diskutil list` in terminal?

**Comment by corpnewt** [comment]
Alternatively, you could save the following in a file named "settings.json" inside the Scripts directory (which disables the auto-EFI locating):
```json
{
  "auto_efi" : false
}
```

**Comment by ghost** [comment]
![2019-03-01 10 49 41](https://user-images.githubusercontent.com/24504662/53613082-e410e800-3c0f-11e9-9d34-86465708afe8.png)
![2019-03-01 10 52 13](https://user-images.githubusercontent.com/24504662/53613154-1d495800-3c10-11e9-9910-42052c2fb6e7.png)
three disks , one for macOS , one for windows and one for data

**Comment by ghost** [comment]
> settings.json

it works . thanks a lot!

**Comment by corpnewt** [comment]
Was the booted Clover located at `disk0s1`?  If you booted Clover from a USB, then removed that USB, it will fail to find it (as the actual disk is not present anymore).

I'm glad the settings adjustment worked.
