### ISSUE TITLE
Invalid Disk when selecting disk

### ISSUE THREAD

**Issue by animalelder** [corpnewt/EssentialsList#4]
I have used this in the past on a different build. When I choose my startup disk, it says it is invalid. It is my main drive, it has the EFI, and the EFI happens to be mounted. So I unmounted the EFI partition, closed the script, and tried again.

Same issue. I re-checked permissions and tried again. Still says invalid disk. Just thought you might want to know. It was a really nice script.

**Comment by corpnewt** [comment]
Can you send your `diskutil list` output?

-CorpNewt

**Comment by corpnewt** [comment]
Should be fixed with [this commit](https://github.com/corpnewt/EssentialsList/commit/399bfc5b858aba60e4b2cc84abdeb61c2aaa8c0d).

-CorpNewt
