### ISSUE TITLE
OpenCore version please

### ISSUE THREAD

**Issue by DWomack** [corpnewt/EssentialsList#5]
I appreciate your work!

Could you please create an OpenCore version of this utility.  It would be very helpful.

Thanks

Dennis

**Comment by corpnewt** [comment]
I know this is a late response - but I added support for OC some time ago in [this commit](https://github.com/corpnewt/EssentialsList/commit/d74bd6c1265bec70c671641af87eef479954e77c#diff-c466f9937ae95ad8c9e05362dd335e7fb0afceaef89209043f75616fce9b82bb).

-CorpNewt

**Comment by DWomack** [comment]
Thank you for your hard work. 

I really appreciate it. 


Dennis
